name: Test Kompilacji Produkcyjnej

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu źródłowego
        uses: actions/checkout@v4

      - name: Instalacja menedżera pakietów pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Inicjalizacja środowiska Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalacja zależności projektowych
        run: pnpm install --no-frozen-lockfile

      - name: Budowanie testowe aplikacji
        run: pnpm prisma generate
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/streamforge"
